namepsace: b4w
name: b4w-<+artifacts.primary.tag>

repo: <+serviceVariables.repo>
frontendImage: <+serviceVariables.frontend_image>
backendImage: <+serviceVariables.backend_image>
tag: <+artifacts.primary.tag>
